server:
  port: 8072

app:
  name: song-svc

logging:
  level:
    com.tananushka.song.svc: DEBUG
    root: INFO

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/song_svc_db"
    username: "postgres"
    password: "1111"
  sql:
    init:
      mode: never


#always, embedded, never

